version: "3"

volumes:
   _postgres_data:

services:
  db:
    image: postgres:13
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/code/
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
